name: Run tests

on: [push, pull_request]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    container:
      #image: robcherry/docker-chromedriver:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3 #Setup Node
        with:
          node-version: '18'

      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'

      - uses: DeLaGuardo/setup-clojure@11.0
        with:
          cli: 1.10.1.693              # Clojure CLI based on tools.deps
          lein: 2.9.1                  # Leiningen
      # - name: run test
      #   env: 
      #     GCLOUD_PROJECT: "my-haggadah"
      #     GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MY_HAGGADAH}}
      #   run: |

      #     which chromedriver
      #     chromedriver --help
      #     ls /usr/bin/google-chrome
      #     which google-chrome
      #     google-chrome --version
      #     chromedriver --version
          #npm install
          # npm install -g firebase-tools
          # npm test
          # npm run test:acceptance 


