name: Run tests

on: [pull_request]

env:
  GCLOUD_PROJECT: "my-haggadah"
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MY_HAGGADAH}}

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: get latest chromedriver version
        run: |
          CHROMEDRIVER_VERSION=`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`

      - name: install chromedriver
        run: |
          CHROMEDRIVER_VERSION=`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`
          mkdir -p /opt/chromedriver-$CHROMEDRIVER_VERSION 
          curl -sS -o /tmp/chromedriver_linux64.zip http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          unzip -qq /tmp/chromedriver_linux64.zip -d /opt/chromedriver-$CHROMEDRIVER_VERSION 
          rm /tmp/chromedriver_linux64.zip 
          chmod +x /opt/chromedriver-$CHROMEDRIVER_VERSION/chromedriver 
          ln -fs /opt/chromedriver-$CHROMEDRIVER_VERSION/chromedriver /usr/local/bin/chromedriver

      - name: install chrome
        run: |
          wget --no-verbose -O /tmp/chrome.deb https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_114.0.5735.198-1_amd64.deb
          sudo apt-get update
          sudo apt-get install -y -f /tmp/chrome.deb
          rm /tmp/chrome.deb


      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list



      - uses: actions/setup-node@v3 #Setup Node
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'maven'


      - name: Cache clojure dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          # List all files containing dependencies:
          key: cljdeps-${{ hashFiles('project.clj') }}

      - name: install firebase tools
        run: npm install -g firebase-tools

      - name: run backend tests
        run: |
            cd functions
            npm install
            touch index.js
            npm run ci
            cd ..

      - name: run frontend tests
        run: |
            npm install
            npm run test:build
            npm run test


      - uses: DeLaGuardo/setup-clojure@11.0
        with:
          cli: 1.10.1.693              # Clojure CLI based on tools.deps
          lein: 2.9.1                  # Leiningen


      # - name: run acceptance test
      #   env:
      #     CHROME_BIN: "/usr/bin/google-chrome"
      #   run: |
      #       npm run release
      #       npm run test:acceptance 


      - name: Upload screenshots on acceptance test fail
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: acceptance-test-snapshots
          path: |
            screenshots
