name: Run tests

on: [push, pull_request]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/day8/chrome-latest:5.0.0
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3 #Setup Node
        with:
          node-version: '18'
      - name: run test
        env: 
          GCLOUD_PROJECT: "my-haggadah"
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MY_HAGGADAH}}
        run: |
          npm install
          npm install -g firebase-tools
          npm test
          npm run test:acceptance 
