name: Run tests

on: [push, pull_request]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    container:
      #image: robcherry/docker-chromedriver:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3 #Setup Node
        with:
          node-version: '18'

      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - run: |
          sudo apt-get update
          sudo apt-get install -y libgconf-2-4 libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libgbm-dev libnss3-dev libxss-dev libasound2

      - uses: browser-actions/setup-chrome@latest

      - uses: DeLaGuardo/setup-clojure@11.0
        with:
          cli: 1.10.1.693              # Clojure CLI based on tools.deps
          lein: 2.9.1                  # Leiningen

      - name: run test

        env:
          CHROME_BIN: "/opt/hostedtoolcache/chromium/latest/x64/chrome"
          GCLOUD_PROJECT: "my-haggadah"
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MY_HAGGADAH}}
        run: |
            npm install
            npm install -g firebase-tools
            npm run test
            npm run release
            cd functions
            npm install
            npm run release
            npm run test
            cd ..
            pwd
            npm run test:acceptance 


